# Generated by Django 2.0.4 on 2018-05-03 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fe_task', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='parent',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
